In [2]:
import numpy as np
import pandas as pd
from ast import literal_eval

In [4]:
path = "./Data/search_grid.csv"
df = pd.read_csv(path, converters={"mapped_zipcodes": literal_eval})

In [5]:
df = df.explode("mapped_zipcodes").reset_index()
df['mapped_zipcodes'] = pd.to_numeric(df['mapped_zipcodes'])

In [6]:
df

    index  grid_lat  grid_lon  mapped_zipcodes
0       0      26.0     -80.5            33182
1       1      28.0     -82.5            33572
2       2      28.0     -82.0            33811
3       3      29.5     -98.5            78154
4       4      30.0     -98.0            78666
..    ...       ...       ...              ...
86     66      45.5    -123.0            97124
87     67      47.0    -122.5            98327
88     68      47.0    -122.0            98390
89     69      47.5    -122.5            98032
90     69      47.5    -122.5            98421

[91 rows x 4 columns]

In [7]:
impact_17 = pd.read_csv("/home/ahimschoot3-gtri/Amazon/impact_score_2017.csv")

FileNotFoundError: [Errno 2] File /home/ahimschoot3-gtri/Amazon/impact_score_2017.csv does not exist: '/home/ahimschoot3-gtri/Amazon/impact_score_2017.csv'

In [5]:
impact_17 = impact_17.join(df.set_index('mapped_zipcodes'), on='zip5').drop(["Unnamed: 0", "index"], axis = 1)

In [6]:
impact_18 = pd.read_csv("/home/ahimschoot3-gtri/Amazon/impact_score_2018.csv")

In [7]:
impact_18 = impact_18.join(df.set_index('mapped_zipcodes'), on='zip5').drop(["Unnamed: 0", "index"], axis = 1)

In [8]:
impact_19 = pd.read_csv("/home/ahimschoot3-gtri/Amazon/impact_score_2019_public_test.csv")
impact_19["impact_score"] = 0

In [9]:
impact_19 = impact_19.join(df.set_index('mapped_zipcodes'), on='zip5').drop(["Unnamed: 0", "index"], axis = 1)

In [11]:
df = pd.concat([impact_17, impact_18,  impact_19], ignore_index=True)
df

         date_key   zip5  impact_score  grid_lat  grid_lon
0      2017-01-01   2722     20.268081      41.5     -71.0
1      2017-01-01   3063     31.794226      43.0     -71.5
2      2017-01-01   7008     22.809754      40.5     -74.0
3      2017-01-01   8518      8.621755      40.0     -75.0
4      2017-01-01   8691     21.099682      40.0     -74.5
...           ...    ...           ...       ...       ...
98670  2019-12-31  97124      0.000000      45.5    -123.0
98671  2019-12-31  98032      0.000000      47.5    -122.5
98672  2019-12-31  98327      0.000000      47.0    -122.5
98673  2019-12-31  98390      0.000000      47.0    -122.0
98674  2019-12-31  98421      0.000000      47.5    -122.5

[98675 rows x 5 columns]