In [6]:
import numpy as np
import os
import pandas as pd
import glob
import h5py
import tables

ModuleNotFoundError: No module named 'tables'

In [11]:
# List all weather data files
weather17 = ["./Data/GFS_2017/" + f for f in os.listdir("./Data/GFS_2017")]
weather18 = ["./Data/GFS_2018/" + f for f in os.listdir("./Data/GFS_2018")]
weather19 = ["./Data/GFS_2019/" + f for f in os.listdir("./Data/GFS_2019")]
grid = "./Data/search_grid.csv"
allweather = weather17 + weather18 + weather19

In [3]:
# Concat into a giant dataframe
weather = pd.concat(map(pd.read_csv, allweather), ignore_index=True)

In [12]:
# Load loc2zip map
loc2zip = pd.read_csv(grid)

In [4]:
weather

,Date,Time,ForecastRange,x,y,lat,lng,5_Wave_Geopotential_Height_isobaric,Absolute_vorticity_isobaric,Apparent_temperature_height_above_ground,...,Ice_water_mixing_ratio_hybrid,Ice_water_mixing_ratio_isobaric,Precipitation_rate_surface,Rain_mixing_ratio_hybrid,Rain_mixing_ratio_isobaric,Snow_mixing_ratio_hybrid,Snow_mixing_ratio_isobaric,Total_cloud_cover_isobaric,Vertical_velocity_geometric_isobaric,Ice_growth_rate_altitude_above_msl
0,20170626,12,0,474,89,45.5,-123.0,5873.937988,0.000094,285.100006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20170626,12,0,475,85,47.5,-122.5,5864.678223,0.000103,286.299988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20170626,12,0,475,86,47.0,-122.5,5867.498047,0.000105,285.700012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20170626,12,0,476,86,47.0,-122.0,5867.658203,0.000103,284.200012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20170626,12,0,477,103,38.5,-121.5,5876.218262,0.000072,286.200012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302465,20190629,12,0,1142,198,40.5,-74.5,5886.802734,0.000084,298.746735,...,0.0,0.0,0.0000,0.0,4.100000e-10,0.0,3.090000e-09,0.0,0.016517,NaN
302466,20190629,12,0,1142,200,40.0,-74.5,5889.842285,0.000082,297.446716,...,0.0,0.0,0.0002,0.0,4.200000e-10,0.0,3.120000e-09,0.0,-0.001483,NaN
302467,20190629,12,0,1144,198,40.5,-74.0,5884.522461,0.000086,297.046722,...,0.0,0.0,0.0009,0.0,4.100000e-10,0.0,3.090000e-09,0.0,0.020817,NaN
302468,20190629,12,0,1154,188,43.0,-71.5,5852.082520,0.000102,294.346741,...,0.0,0.0,0.0001,0.0,3.400000e-10,0.0,2.760000e-09,0.0,0.000617,NaN
302469,20190629,12,0,1156,194,41.5,-71.0,5861.722656,0.000093,293.946716,...,0.0,0.0,0.0002,0.0,3.900000e-10,0.0,3.010000e-09,0.0,0.006017,NaN

In [8]:
# Save as a hdf5 file
weather.to_hdf('weather.h5', key='df', mode='a')

In [9]:
# Load data from hdf5 file
w = pd.read_hdf('weather.h5', 'df')

In [2]:
os.chdir("/home/ahimschoot3-gtri/Amazon/GFS_2017")

In [3]:
df1 = pd.read_csv("gfs_4_20170101_0000_000.csv")
df2 = pd.read_csv("gfs_4_20170101_0600_000.csv")
df3 = pd.read_csv("gfs_4_20170101_1200_000.csv")
df4 = pd.read_csv("gfs_4_20170101_1800_000.csv")

In [4]:
df = pd.concat([df1,df2, df3, df4])

In [5]:
df_multi = df.set_index(['Date','lat', 'lng'])

In [6]:
df_multi.pivot(columns = "Time")

                     ForecastRange             x                   y       \
Time                            0  6  12 18   0    6    12   18   0    6
Date     lat  lng
20170101 26.0 -80.5              0  0  0  0  559  559  559  559  128  128
         28.0 -82.5              0  0  0  0  555  555  555  555  124  124
              -82.0              0  0  0  0  556  556  556  556  124  124
         29.5 -98.5              0  0  0  0  523  523  523  523  121  121
         30.0 -98.0              0  0  0  0  524  524  524  524  120  120
...                            ... .. .. ..  ...  ...  ...  ...  ...  ...
         45.0 -93.5              0  0  0  0  533  533  533  533   90   90
         45.5 -123.0             0  0  0  0  474  474  474  474   89   89
         47.0 -122.5             0  0  0  0  475  475  475  475   86   86
              -122.0             0  0  0  0  476  476  476  476   86   86
         47.5 -122.5             0  0  0  0  475  475  475  475   85   85

                      ... v_component_of_wind_pressure_difference_layer        \
Time                  ...                                            12    18
Date     lat  lng     ...
20170101 26.0 -80.5   ...                                          3.19  4.40
         28.0 -82.5   ...                                          5.19  4.44
              -82.0   ...                                          4.95  4.16
         29.5 -98.5   ...                                         -3.97  1.40
         30.0 -98.0   ...                                         -3.80 -0.28
...                   ...                                           ...   ...
         45.0 -93.5   ...                                         -1.73 -1.14
         45.5 -123.0  ...                                          3.99  1.32
         47.0 -122.5  ...                                          3.49 -3.69
              -122.0  ...                                          1.81 -1.08
         47.5 -122.5  ...                                         -1.93 -6.24

                     v_component_of_wind_sigma                    \
Time                                        0     6     12    18
Date     lat  lng
20170101 26.0 -80.5                       1.90  3.68  2.13  4.21
         28.0 -82.5                       0.14  3.09  3.22  4.18
              -82.0                       0.16  3.84  2.98  3.87
         29.5 -98.5                       2.24  1.71 -4.07  1.16
         30.0 -98.0                       3.31  1.74 -4.17 -0.46
...                                        ...   ...   ...   ...
         45.0 -93.5                       5.04  5.20 -0.04 -0.96
         45.5 -123.0                      3.18  3.05  3.36  1.31
         47.0 -122.5                      5.55  3.92  2.33 -2.46
              -122.0                      2.08  1.25  1.67 -0.57
         47.5 -122.5                      6.67  0.35 -1.39 -5.40

                     v_component_of_wind_tropopause                        \
Time                                             0          6          12
Date     lat  lng
20170101 26.0 -80.5                            -2.3  -4.000000  -2.900000
         28.0 -82.5                            -1.8   0.700000  -0.800000
              -82.0                            -2.4   0.400000  -1.200000
         29.5 -98.5                             9.4  38.700001  43.000000
         30.0 -98.0                             9.3  39.400002  43.799999
...                                             ...        ...        ...
         45.0 -93.5                           -27.5 -15.700000   0.400000
         45.5 -123.0                            3.2   6.200000  -2.900000
         47.0 -122.5                            4.4  -2.600000  -2.100000
              -122.0                            5.4   0.400000  -2.200000
         47.5 -122.5                            5.0  -1.300000  -3.000000


Time                         18
Date     lat  lng
20170101 26.0 -80.5   -1.000000
         28.0 -82.5    2.900000
              -82.0    2.800000
         29.5 -98.5   39.799999
         30.0 -98.0   39.299999
...                         ...
         45.0 -93.5   16.200001
         45.5 -123.0  -1.400000
         47.0 -122.5  -0.200000
              -122.0   1.500000
         47.5 -122.5  -2.300000

[70 rows x 376 columns]

In [8]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
all_filenames.sort()
all_df = [pd.read_csv(f) for f in all_filenames]
all_df = pd.concat(all_df)
all_df = all_df.set_index(["Date", "lat", "lng"], append = True)
#all_df = all_df.pivot(columns = "Time")
#every_four = [pd.concat(all_df[i:i+4]) for i in range(0, len(all_df), 4)]
#combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames], axis = 1)
#combined_csv.to_csv("combined_weather.csv", index = False, encoding = "utf-8-sig")

In [14]:
all_df

NameError: name 'all_df' is not defined